### ISSUE TITLE
Doesn't compile on Ubuntu 14.04 due to problem with libtool default

### ISSUE THREAD

**Issue by benvarkey** [fangism/hackt#26]
Running `make haccreate` from the `<build_dir>/src` would result in the following error:

```
/usr/bin/ld: main/haccreate-create.o: undefined reference to symbol 'HAC::entity::module::is_created() const'
//ramdisk/hackt/src/.libs/libhacktparsers.so.0: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
```

Turns out `libtool` was ignoring the library dependencies listed in `libhacktlib.la` when generating the linking command. With Fang's help (and stackoverflow :P), we traced it back to `<src_dir>/config/libtool.m4` that set `link_all_deplibs=no` at some places. Changing all these to `link_all_deplibs=no` and re-making fixed the issue.

**Comment by fangism** [comment]
Keep running into this issue a lot.  Apparently, Ubuntu is a popular linux distro.

Just to clarify:

after bootstrapping and before configure:

```
sed -i.orig -e '/link_all_deplibs/s|=no|=yes|' config/libtool.m4
```

**Comment by fangism** [comment]
Alternatively, fix the generated `libtool` after `configure`, before `make`:

```
sed -i.orig -e '/^link_all_deplibs=/s|=no|=yes|' libtool
```

This doesn't require user to re-`libtoolize`.
