### ISSUE TITLE
Doesn't compile with Bison 3.0.2

### ISSUE THREAD

**Issue by benvarkey** [fangism/hackt#27]
During make I get the following:

```
/bin/sh ../libtool   --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I/home/dev/hackt/src  -I/home/dev/hackt/src       -pipe -ansi -pedantic-errors -Wold-style-cast -Woverloaded-virtual -W -Wextra -Wall -Wundef -Wshadow -Wno-unused-parameter -Wpointer-arith -Wcast-qual -Wcast-align -Wconversion -Werror -Wno-unused -Wno-old-style-cast -Wno-shadow -Wno-error -Wno-conversion -g -O3 -MT parser/libhacktparsers_la-hackt-parse-real.lo -MD -MP -MF parser/.deps/libhacktparsers_la-hackt-parse-real.Tpo -c -o parser/libhacktparsers_la-hackt-parse-real.lo `test -f 'parser/hackt-parse-real.cc' || echo '/home/dev/hackt/src/'`parser/hackt-parse-real.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/home/dev/hackt/src -I/home/dev/hackt/src -pipe -ansi -pedantic-errors -Wold-style-cast -Woverloaded-virtual -W -Wextra -Wall -Wundef -Wshadow -Wno-unused-parameter -Wpointer-arith -Wcast-qual -Wcast-align -Wconversion -Werror -Wno-unused -Wno-old-style-cast -Wno-shadow -Wno-error -Wno-conversion -g -O3 -MT parser/libhacktparsers_la-hackt-parse-real.lo -MD -MP -MF parser/.deps/libhacktparsers_la-hackt-parse-real.Tpo -c parser/hackt-parse-real.cc  -fPIC -DPIC -o parser/.libs/libhacktparsers_la-hackt-parse-real.o
parser/hackt-parse.cc:2632:30: error: macro "yylex" requires 2 arguments, but only 1 given
     }
                              ^
In file included from parser/hackt-parse.yy:29:0:
./parser/hackt-parse.output.hh:24:1: error: zero-size array 'yysss'
 };  /* end yysss */
 ^
parser/hackt-parse.cc: In function 'int hackt_parse()':
parser/hackt-parse.cc:2632:16: error: 'yylex' was not declared in this scope
     }
                ^
parser/hackt-parse.cc:2635:58: error: '_lexer_state' was not declared in this scope
     {
                                                          ^
parser/hackt-parse.yy:847:59: error: '_lexer_state' was not declared in this scope
    yyerror(msg);
                                                           ^
parser/hackt-parse.cc:5861:74: error: '_lexer_state' was not declared in this scope
       yyerror (YY_("syntax error"));
                                                                          ^
parser/hackt-parse.cc:6005:74: error: '_lexer_state' was not declared in this scope
   yyerror (YY_("memory exhausted"));
                                                                          ^
make[3]: *** [parser/libhacktparsers_la-hackt-parse-real.lo] Error 1
```
